# Generated by Django 6.0.6 on 2026-07-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Admin tug'ilgan sana (kamida 19 yosh bo'lishi shart).", null=True),
        ),
    ]
