# Generated by Django 6.0.6 on 2026-06-06 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('address', models.TextField()),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, help_text="Mijozning kompaniyadan qarzi (agar bo'lsa)", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Buyurtma qilingan suv soni', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('DELIVERING', "Yo'lda / Yetkazilmoqda"), ('DELIVERED', 'Yetkazib berildi'), ('CANCELED', 'Bekor qilindi')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('liters', models.DecimalField(decimal_places=2, help_text='Suv hajmi (litrda)', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Omborda bormi?')),
            ],
            options={
                'verbose_name': 'Suv',
                'verbose_name_plural': 'Suvlar',
                'ordering': ['brand_name'],
            },
        ),
    ]
